"""brainfuck_talk.py - the fleet's Brainfuck phrasebook.

The robots "talk" in Brainfuck: every phrase is a real Brainfuck program that
prints its words, and a robot says it by beeping the program's source - one
tone per symbol, pitched to that robot's voice. Only the utterance number
travels over IR or WiFi; RIFT's log shows the program and what it prints.

Utterances 0-6 are the phrases, 7-13 the matching replies:
    0 hello  1 how are you  2 happy  3 curious  4 sleepy  5 let's play  6 bye

Run this after changing PHRASES. It writes the same talk_bf.h into every
robot sketch it finds next to this repo (and Fleet/talk_bf.json for RIFT),
checking each program with an interpreter first.

Usage:  python Fleet/brainfuck_talk.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
GITHUB = os.path.abspath(os.path.join(HERE, "..", ".."))

# (name, phrase text, reply text)
PHRASES = [
    ("hello",       "hi",   "hi!"),
    ("how are you", "hru?", "ok:)"),
    ("happy",       "yay",  "yay!"),
    ("curious",     "hm?",  "oh!"),
    ("sleepy",      "zzz",  "nite"),
    ("play",        "play", "yes!"),
    ("bye",         "bye",  "bye!"),
]

# Sketches that speak or log the phrases (relative to the GitHub folder).
SKETCHES = [
    "NORA-Robot-v00/scripts/arduino",
    "NORA-Robot-v00/scripts/esp32",
    "IDA-Robot-v00/IDA-Robot-v00/scripts/IDA",
    "MILA/scripts/MILA",
    "KIDA-Robot-v01/scripts/arduino/arduino00",
    "DREAM/dream_sensors",
    "ARM-Robot-v01/scripts/arm",
    "RIFT/arduino/rift_link",
]

# One tone per symbol (Hz before the robot's voice scaling) and its length
# (ms). '.' - "print" - is the long high blip, so you hear each letter land.
TONES = {"+": 1568, "-": 784, ">": 1319, "<": 1047, "[": 880, "]": 1175, ".": 2093, ",": 523}
LENGTHS = {".": 80}
DEFAULT_MS = 28
GAP_MS = 10


def _adjust(diff):
    return ("+" if diff > 0 else "-") * abs(diff)


def compile_text(text):
    """A short Brainfuck program printing text: cell 1 holds the character,
    cell 0 is a loop counter used to make big jumps (the link.bf style)."""
    code, value = ">", 0
    for ch in text:
        target = ord(ch)
        diff = target - value
        best = _adjust(diff)
        # a counter loop: <aaaa[>bbbb<-]> adds a*b (or subtracts), then nudge
        for a in range(2, 16):
            for b in range(1, 32):
                for sign in (1, -1):
                    rest = diff - sign * a * b
                    cand = "<" + "+" * a + "[>" + ("+" if sign > 0 else "-") * b + "<-]>" + _adjust(rest)
                    if len(cand) < len(best):
                        best = cand
        code += best + "."
        value = target
    return code[2:] if code.startswith("><") else code   # don't step right just to step back


def run_bf(code, max_steps=None):
    """Minimal interpreter, enough to check the generated programs. max_steps
    bounds it for programs heard over the air (Fleet/near_map.py)."""
    tape, ptr, ip, out, jump, stack = [0] * 64, 0, 0, [], {}, []
    for i, c in enumerate(code):
        if c == "[":
            stack.append(i)
        elif c == "]":
            j = stack.pop()
            jump[i], jump[j] = j, i
    steps = 0
    while ip < len(code):
        steps += 1
        if max_steps is not None and steps > max_steps:
            raise ValueError("Brainfuck program ran too long")
        c = code[ip]
        if c == ">": ptr += 1
        elif c == "<": ptr -= 1
        elif c == "+": tape[ptr] = (tape[ptr] + 1) % 256
        elif c == "-": tape[ptr] = (tape[ptr] - 1) % 256
        elif c == ".": out.append(chr(tape[ptr]))
        elif c == "[" and tape[ptr] == 0: ip = jump[ip]
        elif c == "]" and tape[ptr] != 0: ip = jump[ip]
        ip += 1
    return "".join(out)


def utterances():
    """[(index, name, kind, text, code)] - phrases 0-6 then replies 7-13."""
    out = []
    for i, (name, said, reply) in enumerate(PHRASES):
        out.append((i, name, "phrase", said, compile_text(said)))
    for i, (name, said, reply) in enumerate(PHRASES):
        out.append((7 + i, name, "reply", reply, compile_text(reply)))
    for idx, name, kind, text, code in out:
        assert run_bf(code) == text, (idx, code)
    return out


def seconds(code):
    return sum(LENGTHS.get(c, DEFAULT_MS) + GAP_MS for c in code) / 1000


def header(utts):
    lines = [
        "// talk_bf.h - the fleet's Brainfuck phrasebook. GENERATED by",
        "// RIFT/Fleet/brainfuck_talk.py - edit PHRASES there and rerun, don't edit here.",
        "//",
        "// Every phrase is a Brainfuck program that prints its words; a robot says it",
        "// by beeping the source, one tone per symbol (bfToneHz/bfToneMs), scaled to",
        "// its own voice. Utterances 0-6 are phrases, 7-13 the matching replies:",
        "// 0 hello, 1 how are you, 2 happy, 3 curious, 4 sleepy, 5 let's play, 6 bye.",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        "#define TALK_UTTERANCES 14",
        "#define TALK_GAP_MS %d" % GAP_MS,
        "",
    ]
    for idx, name, kind, text, code in utts:
        lines.append('static const char TALK_BF_%d[] PROGMEM = "%s";  // %s %s -> "%s" (%.1f s)'
                     % (idx, code, name, kind, text, seconds(code)))
    lines += ["", "static const char* const TALK_BF[TALK_UTTERANCES] PROGMEM = {",
              "  " + ", ".join("TALK_BF_%d" % u[0] for u in utts), "};", ""]
    lines.append("// What each utterance prints, for logs and web pages.")
    lines.append("static const char* const TALK_TEXT[TALK_UTTERANCES] = {")
    lines.append("  " + ", ".join('"%s"' % u[3] for u in utts))
    lines += ["};", ""]
    lines.append("// Symbol n (0 = end) of utterance u, read from flash.")
    lines.append("static inline char talkSymbol(uint8_t u, uint16_t n) {")
    lines.append("  const char* p = (const char*)pgm_read_ptr(&TALK_BF[u]);")
    lines.append("  return (char)pgm_read_byte(p + n);")
    lines.append("}")
    lines.append("")
    lines.append("static inline uint16_t bfToneHz(char c) {")
    lines.append("  switch (c) {")
    for c, hz in TONES.items():
        lines.append("    case '%s': return %d;" % (c, hz))
    lines.append("  }")
    lines.append("  return 0;")
    lines.append("}")
    lines.append("")
    lines.append("static inline uint16_t bfToneMs(char c) { return c == '.' ? %d : %d; }" % (LENGTHS["."], DEFAULT_MS))
    lines.append(PLAYER)
    return "\n".join(lines) + "\n"


PLAYER = """
// ---- Player ----
// Non-blocking: talkStart(u), then call talkStep(pin, voicePct) every loop;
// each symbol is a tone() of bfToneHz * voicePct / 100. Returns false once
// it's quiet.
static int8_t        talkUtterance = -1;
static uint16_t      talkPos       = 0;
static unsigned long talkNextMs    = 0;

static inline void talkStart(int u) {
  if (u < 0 || u >= TALK_UTTERANCES) return;
  talkUtterance = u;
  talkPos       = 0;
  talkNextMs    = 0;
}

static inline bool talkStep(uint8_t pin, uint8_t voicePct) {
  if (talkUtterance < 0) return false;
  if (millis() < talkNextMs) return true;
  char c = talkSymbol(talkUtterance, talkPos++);
  if (!c) { talkUtterance = -1; noTone(pin); return false; }
  uint16_t ms = bfToneMs(c);
  tone(pin, (unsigned long)bfToneHz(c) * voicePct / 100, ms);
  talkNextMs = millis() + ms + TALK_GAP_MS;
  return true;
}

// Blocking: plays utterance u through the robot's own beep(freq, ms), for
// sketches whose beep() has to pause something (IRremote shares Timer2).
static inline void talkPlayBlocking(int u, uint8_t voicePct, void (*beep)(unsigned int, unsigned int)) {
  if (u < 0 || u >= TALK_UTTERANCES) return;
  for (uint16_t n = 0;; n++) {
    char c = talkSymbol(u, n);
    if (!c) break;
    beep((unsigned long)bfToneHz(c) * voicePct / 100, bfToneMs(c));
    delay(TALK_GAP_MS);
  }
}"""


def main():
    utts = utterances()
    for idx, name, kind, text, code in utts:
        print("%2d %-12s %-6s %-5s %4.1fs  %s" % (idx, name, kind, text, seconds(code), code))
    h = header(utts)
    for rel in SKETCHES:
        folder = os.path.join(GITHUB, rel)
        if os.path.isdir(folder):
            with open(os.path.join(folder, "talk_bf.h"), "w", newline="\n") as f:
                f.write(h)
            print("wrote", rel + "/talk_bf.h")
        else:
            print("skipped (not found)", rel)
    with open(os.path.join(HERE, "talk_bf.json"), "w") as f:
        json.dump([{"index": i, "name": n, "kind": k, "text": t, "bf": c} for i, n, k, t, c in utts], f, indent=1)
    print("wrote Fleet/talk_bf.json")


if __name__ == "__main__":
    main()
